

# # Main API Schemas

# # POST request
# # Define the expected JSON input, which does not include system-generated IDs
# class UserCreate(APIBase):
#     external_id: Optional[str] = None
#     user_name: str
#     display_name: Optional[str] = None
#     active: Optional[bool] = True

#     # Nested Schemas

#     name: Optional[NameScim] = None
#     # use validation constraint mandated by the SCIM RFC
#     emails: list[EmailScim] = APIField(min_items=1) # SCIM requires at least one email
#     addresses: list[AddressScim] = APIField(default_factory=list)
#     phone_numbers: list[PhoneNumberScim] = APIField(default_factory=list)

#     roles: list[RoleScim] = APIField(default_factory=list)
#     entitlements: list[EntitlementScim] = APIField(default_factory=list)

#     # Enterprise

#     employee_number: Optional[str] = None
#     cost_center: Optional[str] = None
#     organization: Optional[str] = None
#     division: Optional[str] = None
#     department: Optional[str] = None
#     manager: Optional[ManagerScim] = None


# # GET response schema
# # Defines the output JSON structure. It includes ID and Meta fields generated by the system
# class UserPublic(APIResponse):

#     id: str
#     user_name: str
#     schemas: list[str] 

#     # Optional Fields
#     external_id: Optional[str] = None
#     display_name: Optional[str] = None
#     active: Optional[bool] = True


#     # Nested schema
#     name: Optional[NameScim] = None
#     emails: list[EmailScim] 
#     meta: MetaScim
#     addresses: list[AddressScim] = APIField(default_factory=list)
#     phone_numbers: list[PhoneNumberScim] = APIField(default_factory=list)

#     # enterprise
#     employee_number: Optional[str] = None
#     cost_center: Optional[str] = None
#     organization: Optional[str] = None
#     division: Optional[str] = None
#     department: Optional[str] = None
#     manager: Optional[ManagerScim] 

#     photos: list[PhotoScim] = APIField(default_factory=list)
#     ims: list[ImScim] = APIField(default_factory = list)
#     roles: list[RoleScim] = APIField(default_factory=list)
#     entitlements: list[EntitlementScim] = APIField(default_factory=list)
#     groups: list[GroupRefScim] = APIField(default_factory=list)



#     # map data from SQLModel to ORM object
#     model_config = {"from_attributes": True}
