from typing import Optional
from pydantic import Field
from app.schemas.api_response import APIResponse
from app.schemas.sub_schemas import (
    NameScim,
    EmailScim,
    PhoneNumberScim,
    AddressScim,
    ImScim,
    PhotoScim,
    RoleScim,
    EntitlementScim,
    GroupRefScim,
    ManagerScim,
    MetaScim
)
# GET response schema
# Defines the output JSON structure. It includes ID and Meta fields generated by the system
class UserPublic(APIResponse):

    id: str
    user_name: str
    schemas: list[str] 

    # Optional Fields
    external_id: Optional[str] = None
    display_name: Optional[str] = None
    active: Optional[bool] = True


    # Nested schema
    name: Optional[NameScim] = None
    emails: list[EmailScim] 
    meta: MetaScim
    addresses: list[AddressScim] = Field(default_factory=list)
    phone_numbers: list[PhoneNumberScim] = Field(default_factory=list)

    # enterprise
    employee_number: Optional[str] = None
    cost_center: Optional[str] = None
    organization: Optional[str] = None
    division: Optional[str] = None
    department: Optional[str] = None
    manager: Optional[ManagerScim] 

    photos: list[PhotoScim] = Field(default_factory=list)
    ims: list[ImScim] = Field(default_factory = list)
    roles: list[RoleScim] = Field(default_factory=list)
    entitlements: list[EntitlementScim] = Field(default_factory=list)
    groups: list[GroupRefScim] = Field(default_factory=list)



    # map data from SQLModel to ORM object
    model_config = {"from_attributes": True}