from typing import Optional
from pydantic import Field
from app.schemas.api_response import APIResponse
from app.schemas.sub_schemas import (
    NameScim,
    EmailScim,
    PhoneNumberScim,
    AddressScim,
    ImScim,
    PhotoScim,
    RoleScim,
    EntitlementScim,
    GroupRefScim,
    ManagerScim,
    MetaScim,
    EnterpriseExtensionScim
)
# GET response schema
# Defines the output JSON structure. It includes ID and Meta fields generated by the system
class UserPublic(APIResponse):

    id: str
    user_name: str
    schemas: list[str] 

    # Optional Fields
    external_id: Optional[str] = None
    display_name: Optional[str] = None
    active: Optional[bool] = True

#  Simple Optional SCIM Attributes 
    # locale: Optional[str] = None
    # timezone: Optional[str] = None
    # nick_name: Optional[str] = None
    # profile_url: Optional[str] = None
    # title: Optional[str] = None
    # user_type: Optional[str] = None
    # preferred_language: Optional[str] = None


    # Nested schema
    name: Optional[NameScim] = None
    emails: list[EmailScim] = Field(default_factory=list)
    meta: Optional[MetaScim] # will NOT be stored in the database
    addresses: list[AddressScim] = Field(default_factory=list)
    phone_numbers: list[PhoneNumberScim] = Field(default_factory=list)

    # enterprise
    enterprise_extension: Optional[EnterpriseExtensionScim] = Field(
        alias="urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
    )
    # employee_number: Optional[str] = None
    # cost_center: Optional[str] = None
    # organization: Optional[str] = None
    # division: Optional[str] = None
    # department: Optional[str] = None
    # manager: Optional[ManagerScim] 

    # photos: list[PhotoScim] = Field(default_factory=list)
    # ims: list[ImScim] = Field(default_factory = list)
    # roles: list[RoleScim] = Field(default_factory=list)
    # entitlements: list[EntitlementScim] = Field(default_factory=list)
    # groups: list[GroupRefScim] = Field(default_factory=list)


