from pydantic import BaseModel, Field as APIField
from typing import Optional
from datetime import datetime
#API Sub-Schema

class NameScim(BaseModel):
    formatted: Optional[str] = None
    familyName: str
    givenName: str
    middleName: Optional[str] = None 
    honorificPrefix: Optional[str] = None
    honorificSuffix: Optional[str] = None

class EmailScim(BaseModel):
    value:str
    display:Optional[str] = None
    type: Optional[str] = None
    primary: Optional[bool] = None

    #Output/ GET
class MetaScim(BaseModel):
    
    resourceType: str
    created: datetime
    lastModified: datetime 
    version: Optional[str] = None
    location: Optional[str] = None

class AddressScim(BaseModel):
    # All fields are optional
    formatted: Optional[str] = None
    streetAddress: Optional[str] = None
    locality: Optional[str] = None
    region: Optional[str] = None
    postalCode: Optional[str] = None
    country: Optional[str] = None
    type: Optional[str] = None
    primary: Optional[bool] = None # Defaulting to None/NULL in DB

class ManagerScim(BaseModel):
    value: Optional[str] = None
    ref: Optional[str] = APIField(default=None, alias="$ref")
    displayName: Optional[str] = None

class phoneNumberScim(BaseModel):
    value: str = None
    display: Optional[str] = None
    type: Optional[str] = None




# Main API Schemas

# POST request
# Define the expected JSON input, which does not include system-generated IDs
class UserCreate(BaseModel):
    externalId: Optional[str] = None
    userName: str
    displayName: Optional[str] = None
    active: Optional[bool] = True

    # Nested Schemas

    name: Optional[NameScim] = None
    # use validation constraint mandated by the SCIM RFC
    emails: list[EmailScim] = APIField(min_items=1) # SCIM requires at least one email
    addresses: list[AddressScim] = APIField(default_factory=list)
    phoneNumbers: list[phoneNumberScim] = APIField(default_factory=list)

    # Enterprise

    employeeNumber: Optional[str] = None
    costCenter: Optional[str] = None
    organization: Optional[str] = None
    division: Optional[str] = None
    department: Optional[str] = None
    manager: Optional[ManagerScim] 


# GET response schema
# Defines the output JSON structure. It includes ID and Meta fields generated by the system
class UserPublic(BaseModel):

    id: str
    userName: str
    schemas: list[str] 

    # Optional Fields
    externalId: Optional[str] = None
    displayName: Optional[str] = None
    active: Optional[bool] = True


    # Nested schema
    name: Optional[NameScim] = None
    emails: list[EmailScim] 
    meta: MetaScim
    addresses: list[AddressScim] = APIField(default_factory=list)
    phoneNumbers: list[phoneNumberScim] = APIField(default_factory=list)

    # enterprise
    employeeNumber: Optional[str] = None
    costCenter: Optional[str] = None
    organization: Optional[str] = None
    division: Optional[str] = None
    department: Optional[str] = None
    manager: Optional[ManagerScim] 


    # map data from SQLModel to ORM object
    model_config = {"from_attributes": True}
